name: chatbot_flutter_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dash_chat_2: ^0.0.21
  http: ^1.2.1
  chat_gpt_sdk: ^3.0.9
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: FF_Meta
      fonts:
        - asset: assets/fonts/FF_Meta.ttf
          weight: 700

